auto-table:
  enable: true
  auto-drop-column: true
server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auto-table?useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver