package org.dromara.autotable.test.core.unit.builder;

import org.dromara.autotable.annotation.enums.DefaultValueEnum;
import org.dromara.autotable.core.AutoTableGlobalConfig;
import org.dromara.autotable.core.config.PropertyConfig;
import org.dromara.autotable.core.converter.DatabaseTypeAndLength;
import org.dromara.autotable.core.strategy.ColumnMetadata;
import org.dromara.autotable.core.strategy.IStrategy;
import org.dromara.autotable.strategy.pgsql.PgsqlStrategy;
import org.dromara.autotable.strategy.pgsql.builder.ColumnSqlBuilder;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.Collections;

import static org.junit.jupiter.api.Assertions.*;

/**
 * PgSQL ColumnSqlBuilder 单元测试
 */
public class PgsqlColumnSqlBuilderTest {

    @BeforeEach
    void setUp() {
        IStrategy.setCurrentStrategy(new PgsqlStrategy());
    }

    @AfterEach
    void tearDown() {
        IStrategy.clean();
        AutoTableGlobalConfig.clear();
    }

    private ColumnMetadata makeColumn(String name, String type, Integer length) {
        ColumnMetadata column = new ColumnMetadata();
        column.setName(name);
        column.setType(new DatabaseTypeAndLength(type, length, null, Collections.emptyList()));
        return column;
    }

    @Test
    void testBuildSql_simpleNullableColumn() {
        ColumnMetadata column = makeColumn("name", "varchar", 100);
        column.setNotNull(false);

        String sql = ColumnSqlBuilder.buildSql(column);

        assertTrue(sql.contains("\"name\""), "应包含列名");
        assertTrue(sql.contains("varchar(100)"), "应包含类型");
        assertFalse(sql.contains("NOT NULL"), "不应包含 NOT NULL");
        assertFalse(sql.contains("DEFAULT"), "不应包含 DEFAULT");
    }

    @Test
    void testBuildSql_notNullColumn() {
        ColumnMetadata column = makeColumn("age", "int4", null);
        column.setNotNull(true);

        String sql = ColumnSqlBuilder.buildSql(column);

        assertTrue(sql.contains("NOT NULL"));
    }

    @Test
    void testBuildSql_withCustomDefault() {
        ColumnMetadata column = makeColumn("status", "varchar", 20);
        column.setDefaultValueType(null);
        column.setDefaultValue("'active'");

        String sql = ColumnSqlBuilder.buildSql(column);

        assertTrue(sql.contains("DEFAULT 'active'"));
    }

    @Test
    void testBuildSql_withDefaultNull() {
        ColumnMetadata column = makeColumn("deleted", "int4", null);
        column.setDefaultValueType(DefaultValueEnum.NULL);

        String sql = ColumnSqlBuilder.buildSql(column);

        assertTrue(sql.contains("DEFAULT NULL"));
    }

    @Test
    void testBuildSql_withDefaultEmptyString() {
        ColumnMetadata column = makeColumn("remark", "varchar", 255);
        column.setDefaultValueType(DefaultValueEnum.EMPTY_STRING);

        String sql = ColumnSqlBuilder.buildSql(column);

        assertTrue(sql.contains("DEFAULT ''"));
    }

    @Test
    void testBuildSql_autoIncrementByDefault() {
        ColumnMetadata column = makeColumn("id", "int8", null);
        column.setAutoIncrement(true);
        column.setNotNull(true);

        String sql = ColumnSqlBuilder.buildSql(column);

        assertTrue(sql.contains("GENERATED BY DEFAULT AS IDENTITY"), "应使用 BY DEFAULT");
        assertFalse(sql.contains("NOT NULL"), "自增列不应输出 NOT NULL");
        assertFalse(sql.contains("DEFAULT NULL"), "自增列不应输出 DEFAULT NULL");
        assertFalse(sql.contains("DEFAULT '"), "自增列不应输出 DEFAULT 值");
    }

    @Test
    void testBuildSql_autoIncrementAlways() {
        // 配置为 always 模式
        AutoTableGlobalConfig.instance().getAutoTableProperties().getPgsql()
                .setPkAutoIncrementType(PropertyConfig.PgsqlConfig.PgsqlPkAutoIncrementType.always);

        ColumnMetadata column = makeColumn("id", "int8", null);
        column.setAutoIncrement(true);

        String sql = ColumnSqlBuilder.buildSql(column);

        assertTrue(sql.contains("GENERATED ALWAYS AS IDENTITY"), "应使用 ALWAYS");
    }

    @Test
    void testBuildSql_withComment() {
        ColumnMetadata column = makeColumn("name", "varchar", 100);
        column.setComment("用户名称");

        String sql = ColumnSqlBuilder.buildSql(column);

        // 注释由 COMMENT ON 语句单独处理，列定义 SQL 中不应包含注释
        assertFalse(sql.contains("COMMENT"), "列定义 SQL 中不应包含 COMMENT");
    }

    @Test
    void testBuildSql_noDefaultNoNotNull() {
        ColumnMetadata column = makeColumn("data", "text", null);

        String sql = ColumnSqlBuilder.buildSql(column);

        // 只包含列名和类型
        assertTrue(sql.contains("\"data\""));
        assertTrue(sql.contains("text"));
        assertFalse(sql.contains("NOT NULL"));
        assertFalse(sql.contains("DEFAULT"));
    }
}
