auto-table:
  enable: true
  auto-drop-column: true
  record-sql:
    # 开启SQL记录
    enable: true
    # 当前版本（此处可保持与计划上线的版本号一致，方便管理SQL文件）
    version: 1.0.0
    # 记录到文件
    record-type: custom
server:
  port: 9999

solon.dataSources:
  "db_order!": #数据源（!结尾表示 typed=true）
    class: "com.zaxxer.hikari.HikariDataSource"
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/auto_table?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
    username: root
    password: P@ssw0rd
  "db_user": #动态数据源
    class: "org.noear.solon.data.dynamicds.DynamicDataSource"
    strict: true #是否严格的
    default: db_user_r #指定默认的内部数据源
    db_user_r: #内部数据源1
      type: "com.zaxxer.hikari.HikariDataSource"
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/auto_table2?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
      username: root
      password: P@ssw0rd
    db_user_w: #内部数据源2
      type: "com.zaxxer.hikari.HikariDataSource"
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/auto_table3?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
      username: root
      password: P@ssw0rd
  "db_user2": #动态数据源
      class: "org.noear.solon.data.dynamicds.DynamicDataSource"
      strict: true #是否严格的
      default: db_user_r2 #指定默认的内部数据源
      db_user_r2: #内部数据源1
        type: "com.zaxxer.hikari.HikariDataSource"
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/auto_table2?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
        username: root
        password: P@ssw0rd
      db_user_w2: #内部数据源2
        type: "com.zaxxer.hikari.HikariDataSource"
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/auto_table3?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
        username: root
        password: P@ssw0rd

logging:
  level:
    org.dromara: info
