auto-table:
  enable: true
  auto-drop-column: true

spring:
  datasource:
    # master
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/auto-table?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
      username: root
      password: 12345678
    # slave
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
      username: root
      password: 12345678