auto-table:
  enable: true
  auto-drop-column: true
  record-sql:
    # 开启SQL记录
    enable: true
    # 当前版本（此处可保持与计划上线的版本号一致，方便管理SQL文件）
    version: 1.0.0
    # 记录到文件
    record-type: custom
server:
  port: 9999


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auto-table?useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    org.dromara: info
