auto-table:
  enable: true
  mode: create
  auto-drop-column: true
  auto-drop-index: true
  record-sql:
    # 开启SQL记录
    enable: true
    # 当前版本（此处可保持与计划上线的版本号一致，方便管理SQL文件）
    version: 1.0.0
    # 自定义记录方式
    record-type: db

server:
  port: 9999


spring:
  profiles:
    active: oracle23
  datasource:
    url: jdbc:mysql://localhost:3306/auto-table?useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:dm://localhost:5236?schema=test
#    username: dm_user
#    password: Dm888888
#    driver-class-name: dm.jdbc.driver.DmDriver
#    url: jdbc:kingbase8://localhost:54321/test?currentSchema=public&useSSL=false
#    username: postgres
#    password: postgres
#    driver-class-name: com.kingbase8.Driver
logging:
  level:
    org.dromara: info
